In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
dataset=pd.read_csv('criminal_train.csv')

In [3]:
dataset.head()

PERID  IFATHER  NRCH17_2  IRHHSIZ2  IIHHSIZ2  IRKI17_2  IIKI17_2  \
0  25095143        4         2         4         1         3         1   
1  13005143        4         1         3         1         2         1   
2  67415143        4         1         2         1         2         1   
3  70925143        4         0         2         1         1         1   
4  75235143        1         0         6         1         4         1   

   IRHH65_2  IIHH65_2  PRXRETRY    ...     TOOLONG  TROUBUND  PDEN10  COUTYP2  \
0         1         1        99    ...           1         2       1        1   
1         1         1        99    ...           2         2       2        3   
2         1         1        99    ...           2         2       2        3   
3         1         1        99    ...           2         2       1        1   
4         1         1        99    ...           2         2       2        2   

   MAIIN102  AIIND102     ANALWT_C  VESTR  VEREP  Criminal  
0         2         2  3884.805998  40026      1         0  
1         2         2  1627.108106  40015      2         1  
2         2         2  4344.957980  40024      1         0  
3         2         2   792.521931  40027      1         0  
4         2         2  1518.118526  40001      2         0  

[5 rows x 72 columns]

In [4]:
dataset.isnull().values.any()

False

In [5]:
dataset.shape

(45718, 72)

In [6]:
X=dataset.iloc[:,1:-1].values

In [7]:
X.shape

(45718, 70)

In [8]:
y=dataset.iloc[:,-1].values

In [9]:
y.shape

(45718,)

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
sc=StandardScaler()


In [14]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.25,random_state=0)

In [14]:
X_train=sc.fit_transform(X_train)

In [15]:
X_test=sc.transform(X_test)

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [81]:
rfc=RandomForestClassifier(n_estimators=25,random_state=0,criterion='gini',min_samples_split=20,oob_score=True)

In [82]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=20,
            min_weight_fraction_leaf=0.0, n_estimators=30, n_jobs=1,
            oob_score=True, random_state=0, verbose=0, warm_start=False)

In [83]:
y_pred=rfc.predict(X_test)

In [84]:
rfc.score(X_test,y_test)

0.94943132108486439

In [21]:
from sklearn.metrics import confusion_matrix

In [22]:
cm=confusion_matrix(y_test,y_pred)

In [23]:
cm

array([[10415,   189],
       [  377,   449]])

In [24]:
dataset_2=pd.read_csv('criminal_test.csv')

In [25]:
dataset_2.isnull().values.any()

False

In [26]:
dataset_2.shape

(11430, 71)

In [27]:
dataset_2.head()

PERID  IFATHER  NRCH17_2  IRHHSIZ2  IIHHSIZ2  IRKI17_2  IIKI17_2  \
0  66583679        4         0         4         1         2         1   
1  35494679        4         0         4         1         1         1   
2  79424679        2         0         3         1         2         1   
3  11744679        4         0         6         1         2         1   
4  31554679        1         0         4         1         3         1   

   IRHH65_2  IIHH65_2  PRXRETRY  ...    POVERTY3  TOOLONG  TROUBUND  PDEN10  \
0         1         1        99  ...           2        2         2       1   
1         1         1        99  ...           3        2         2       1   
2         1         1        99  ...           1        2         2       2   
3         1         1        99  ...           3        2         2       1   
4         1         1        99  ...           3        2         1       1   

   COUTYP2  MAIIN102  AIIND102      ANALWT_C  VESTR  VEREP  
0        1         2         2  16346.795400  40020      1  
1        1         2         2   3008.863906  40044      2  
2        2         2         2    266.952503  40040      2  
3        1         2         2   5386.928199  40017      1  
4        1         2         2    173.489895  40017      1  

[5 rows x 71 columns]

In [28]:
X_new=dataset_2.iloc[:,1:].values

In [29]:
X_new

array([[  4.00000000e+00,   0.00000000e+00,   4.00000000e+00, ...,
          1.63467954e+04,   4.00200000e+04,   1.00000000e+00],
       [  4.00000000e+00,   0.00000000e+00,   4.00000000e+00, ...,
          3.00886391e+03,   4.00440000e+04,   2.00000000e+00],
       [  2.00000000e+00,   0.00000000e+00,   3.00000000e+00, ...,
          2.66952503e+02,   4.00400000e+04,   2.00000000e+00],
       ..., 
       [  1.00000000e+00,   0.00000000e+00,   5.00000000e+00, ...,
          4.37286522e+03,   4.00220000e+04,   2.00000000e+00],
       [  4.00000000e+00,   0.00000000e+00,   2.00000000e+00, ...,
          6.43616061e+03,   4.00420000e+04,   1.00000000e+00],
       [  4.00000000e+00,   2.00000000e+00,   6.00000000e+00, ...,
          3.63708169e+03,   4.00170000e+04,   2.00000000e+00]])

In [30]:
X_new=sc.transform(X_new)

In [31]:
y_pred_2=rfc.predict(X_new)

In [32]:
y_pred_2

array([0, 0, 0, ..., 0, 0, 0])

In [285]:
df=pd.DataFrame(last,dataset_2['PERID'],dtype='int')

In [286]:
df.head()

0
PERID      
66583679  0
35494679  0
79424679  0
11744679  0
31554679  0

In [287]:
df.to_csv('submission_new_last_final_544412121_final_12355.csv')

In [325]:
df.isnull().values.any()

False

In [37]:
final=pd.read_csv('submission.csv')

In [38]:
final.head()

PERID  Criminal
0  66583679         0
1  35494679         0
2  79424679         0
3  11744679         0
4  31554679         0

In [39]:
final.isnull().values.any()

False

In [305]:
# Using ANN


In [164]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [162]:
X_train.shape

(34288, 24)

In [165]:
classifier=Sequential()

In [166]:
classifier.add(Dense(units=12,init='uniform',activation='relu',input_dim=24))
classifier.add(Dense(units=20,init='uniform',activation='relu'))
classifier.add(Dense(units=20,init='uniform',activation='relu'))
classifier.add(Dense(units=1,init='uniform',activation='sigmoid'))
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

/home/dhama/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=12, activation="relu", input_dim=24, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.
/home/dhama/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=20, activation="relu", kernel_initializer="uniform")`
  
/home/dhama/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=20, activation="relu", kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
/home/dhama/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, activation="sigmoid", kernel_initializer="uniform")`
  after removing the cwd from sys.path.


In [167]:
classifier.fit(X_train,y_train,batch_size=50,epochs=15)

Epoch 1/15
34288/34288 [==============================] - 17s 508us/step - loss: 0.1954 - acc: 0.9331
Epoch 2/15
34288/34288 [==============================] - 4s 108us/step - loss: 0.1119 - acc: 0.9500
Epoch 3/15
34288/34288 [==============================] - 4s 107us/step - loss: 0.1052 - acc: 0.9525
Epoch 4/15
34288/34288 [==============================] - 4s 106us/step - loss: 0.1036 - acc: 0.9533
Epoch 5/15
34288/34288 [==============================] - 4s 108us/step - loss: 0.1025 - acc: 0.9537
Epoch 6/15
34288/34288 [==============================] - 4s 109us/step - loss: 0.1022 - acc: 0.9541
Epoch 7/15
34288/34288 [==============================] - 4s 103us/step - loss: 0.1019 - acc: 0.9541
Epoch 8/15
34288/34288 [==============================] - 3s 102us/step - loss: 0.1013 - acc: 0.9546
Epoch 9/15
34288/34288 [==============================] - 3s 100us/step - loss: 0.1009 - acc: 0.9544
Epoch 10/15
34288/34288 [==============================] - 4s 106us/step - loss: 0.1008 - 

In [168]:
X11.shape

(11430, 24)

In [311]:
y_train.shape

(34288,)

In [169]:
y_pred_last=classifier.predict(X11)

In [171]:
y_pred_last=y_pred_last>0.2

In [172]:
y_pred_last

array([[ True],
       [False],
       [False],
       ..., 
       [False],
       [False],
       [False]], dtype=bool)

In [326]:
df.shape

(11430, 1)

In [339]:
for i in range(0,11430):
    if y_pred_last[[i]]==False:
        y_pred_last[[i]]=0
    else:
        y_pred_last[[i]]=1

In [340]:
y_pred_last

array([[False],
       [False],
       [False],
       ..., 
       [False],
       [False],
       [False]], dtype=bool)

In [336]:
y_pred_last

array([[False],
       [False],
       [False],
       ..., 
       [False],
       [False],
       [False]], dtype=bool)

In [61]:
from sklearn.svm import SVC

In [67]:
sv=SVC(C=10,degree=4)

In [68]:
sv.fit(X_train,y_train)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=4, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [69]:
y_pred_svm=sv.predict(X_test)

In [70]:
sv.score(X_test,y_test)

0.94409448818897634

In [ ]:
#By XGBoost

In [25]:
from xgboost import XGBClassifier

In [26]:
xg=XGBClassifier(learning_rate=0.1,n_estimators=100,max_depth=10,base_score=.5)

In [27]:
xg.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=10, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [28]:
y_pred_xg=xg.predict(X_test)

In [29]:
xg.score(X_test,y_test)

0.94689413823272095

In [136]:
y_xg=xg.predict(X_new)

In [137]:
y_xg

array([0, 0, 0, ..., 0, 0, 0])

In [35]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45718 entries, 0 to 45717
Data columns (total 72 columns):
PERID        45718 non-null int64
IFATHER      45718 non-null int64
NRCH17_2     45718 non-null int64
IRHHSIZ2     45718 non-null int64
IIHHSIZ2     45718 non-null int64
IRKI17_2     45718 non-null int64
IIKI17_2     45718 non-null int64
IRHH65_2     45718 non-null int64
IIHH65_2     45718 non-null int64
PRXRETRY     45718 non-null int64
PRXYDATA     45718 non-null int64
MEDICARE     45718 non-null int64
CAIDCHIP     45718 non-null int64
CHAMPUS      45718 non-null int64
PRVHLTIN     45718 non-null int64
GRPHLTIN     45718 non-null int64
HLTINNOS     45718 non-null int64
HLCNOTYR     45718 non-null int64
HLCNOTMO     45718 non-null int64
HLCLAST      45718 non-null int64
HLLOSRSN     45718 non-null int64
HLNVCOST     45718 non-null int64
HLNVOFFR     45718 non-null int64
HLNVREF      45718 non-null int64
HLNVNEED     45718 non-null int64
HLNVSOR      45718 non-null int64
IRMCDCH

In [ ]:
new_df=dataset[['POVERTY3','IRPRVHLT','IRPINC3','GRPHLTIN','IFATHER','PRVH']]

In [6]:
df_imp = dataset[['IRFAMIN3',
 'POVERTY3',
 'IRPRVHLT',
 'IRPINC3',
 'GRPHLTIN',
 'IFATHER',
 'PRVHLTIN',
 'ANALWT_C',
 'PERID',
 'VESTR',
 'PRXYDATA',
 'IRHHSIZ2',
 'MEDICARE',
 'IRMEDICR',
 'IRMCDCHP',
 'CAIDCHIP',
 'IRHH65_2',
 'IRKI17_2',
 'NRCH17_2',
 'IRFAMSOC',
 'GOVTPROG',
 'OTHINS',
 'IIPRVHLT',
 'HLCNOTMO',
 'COUTYP2',
  'Criminal' ]]

In [7]:
df_imp.shape

(45718, 26)

In [8]:
df_imp.head()

IRFAMIN3  POVERTY3  IRPRVHLT  IRPINC3  GRPHLTIN  IFATHER  PRVHLTIN  \
0         4         2         2        1        99        4         2   
1         1         1         1        1         1        4         1   
2         2         1         2        2        99        4         2   
3         7         3         1        7         1        4         1   
4         2         1         2        1        99        1         2   

      ANALWT_C     PERID  VESTR    ...     IRHH65_2  IRKI17_2  NRCH17_2  \
0  3884.805998  25095143  40026    ...            1         3         2   
1  1627.108106  13005143  40015    ...            1         2         1   
2  4344.957980  67415143  40024    ...            1         2         1   
3   792.521931  70925143  40027    ...            1         1         0   
4  1518.118526  75235143  40001    ...            1         4         0   

   IRFAMSOC  GOVTPROG  OTHINS  IIPRVHLT  HLCNOTMO  COUTYP2  Criminal  
0         2         1       2         1        99        1         0  
1         2         1       2         1        99        3         1  
2         1         1       2         1        99        3         0  
3         2         2       2         1        99        1         0  
4         2         1       2         1        99        2         0  

[5 rows x 26 columns]

In [9]:
X1_new=df_imp.iloc[:,:-1].values

In [10]:
X1_new.shape

(45718, 25)

In [11]:
y1_new=df_imp.iloc[:,-1].values

In [12]:
y1_new.shape

(45718,)

In [15]:
X_train,X_test,y_train,y_test=train_test_split(X1_new,y1_new,test_size=.25,random_state=0)

In [16]:
X_train.shape

(34288, 25)

In [20]:
sc2=StandardScaler()

In [21]:
X_train=sc2.fit_transform(X_train)

In [22]:
X_test=sc2.transform(X_test)

In [23]:
X_test.shape

(11430, 25)

In [24]:
y_test.shape

(11430,)

In [199]:
from sklearn.ensemble import RandomForestClassifier

In [288]:
rf=RandomForestClassifier(n_estimators=25,random_state=1,min_samples_split=30,bootstrap=True,oob_score=True,warm_start=True)

In [289]:
rf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=30,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=1,
            oob_score=True, random_state=1, verbose=0, warm_start=True)

In [290]:
y_this=rf.predict(X_test)

In [291]:
rf.score(X_test,y_test)

0.94969378827646544

In [204]:
df_imp_test = dataset_2[['IRFAMIN3',
 'POVERTY3',
 'IRPRVHLT',
 'IRPINC3',
 'GRPHLTIN',
 'IFATHER',
 'PRVHLTIN',
 'ANALWT_C',
 'PERID',
 'VESTR',
 'PRXYDATA',
 'IRHHSIZ2',
 'MEDICARE',
 'IRMEDICR',
 'IRMCDCHP',
 'CAIDCHIP',
 'IRHH65_2',
 'IRKI17_2',
 'NRCH17_2',
 'IRFAMSOC',
 'GOVTPROG',
 'OTHINS',
 'IIPRVHLT',
 'HLCNOTMO',
 'COUTYP2']]

In [205]:
X11=df_imp_test.iloc[:,:].values

In [206]:
X11.shape

(11430, 25)

In [207]:
X11=sc2.transform(X11)

In [283]:
last=rf.predict(X11)

[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed:    0.0s finished


In [284]:
last

array([0, 0, 0, ..., 0, 0, 0])

In [104]:
from sklearn.naive_bayes import GaussianNB

In [105]:
gb=GaussianNB()

In [106]:
gb.fit(X_train,y_train)

GaussianNB(priors=None)

In [107]:
last=gb.predict(X_test)

In [108]:
gb.score(X_test,y_test)

0.9125109361329834

In [112]:
from sklearn.linear_model import LogisticRegression

In [153]:
lg=LogisticRegression(C=35,random_state=0)

In [154]:
lg.fit(X_train,y_train)

LogisticRegression(C=35, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [155]:
last=lg.predict(X_test)

In [156]:
lg.score(X_test,y_test)

0.93525809273840765

In [157]:
last=lg.predict(X11)